---
# file: roles/sample-app/tasks/main.yml

- name: Create application directory
  file: path={{ app_destination }} state=directory mode=0744

- name: Download application artifacts
  get_url: url={{ item.src }} dest={{ item.dest }} mode=0744
  with_items:
    - { src: '{{ app_binary_url }}', dest: '{{ app_destination }}' }
    - { src: '{{ app_conf_url }}', dest: '{{ app_destination }}' }

- name: Configure launch script
  template: src=launch.sh.j2 dest=/opt/launch.sh mode=0744

- name: Add docker image tag to environment file
  lineinfile: dest=/etc/environment line='IMAGE_VERSION="{{ version }}"'
